version: "3.7"

services:
  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/dev/python/Dockerfile
    env_file:
      - ./.env.dev
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - ./backend:/backend
    networks:
      dev:
        aliases:
            - api.localhost

  frontend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/dev/node/Dockerfile
    environment:
      env_file: ./.env.dev
      NODE_ENV: dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app/:rw
    networks:
      - dev


networks:
  dev:
    driver: bridge