# Generated by Django 3.0.3 on 2020-05-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_auto_20200512_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='change_frequency',
            field=models.CharField(blank=True, choices=[('AL', 'always'), ('HR', 'hourly'), ('DY', 'daily'), ('WK', 'weekly'), ('MN', 'monthly'), ('YR', 'yearly'), ('NR', 'never')], max_length=2, null=True),
        ),
    ]
